// Interactive setup wizard for a new deployment of this DAM.
//
// Collects the organization's identity and service credentials, writes
// .env.local, optionally verifies Supabase/S3 connectivity, and renames the
// seeded space to the organization. Safe to re-run: existing .env.local
// values become the defaults and the old file is backed up first.
//
// Usage: npm run setup            (interactive)
//        npm run setup -- --verify  (also test Supabase + S3 connections)
//
// See docs/SELF_HOSTING.md for the full deployment runbook.
import { createInterface } from "node:readline/promises";
import { existsSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";

const VERIFY = process.argv.includes("--verify");
const ENV_PATH = ".env.local";

if (!process.stdin.isTTY) {
  console.error("setup is interactive — run it in a terminal.");
  process.exit(1);
}

// Existing values (if any) become defaults so re-running is non-destructive.
const existing = {};
if (existsSync(ENV_PATH)) {
  for (const line of readFileSync(ENV_PATH, "utf8").split("\n")) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (match) existing[match[1]] = match[2];
  }
}

const rl = createInterface({ input: process.stdin, output: process.stdout });

async function ask(label, key, { fallback = "", secret = false } = {}) {
  const current = existing[key] ?? fallback;
  const hint = current
    ? secret && current.length > 8
      ? ` [${current.slice(0, 4)}…${current.slice(-4)}]`
      : ` [${current}]`
    : "";
  const answer = (await rl.question(`  ${label}${hint}: `)).trim();
  return answer || current;
}

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

console.log("\nDAM deployment setup");
console.log("Press Enter to keep the value shown in [brackets].\n");

console.log("— Organization —");
const orgName = await ask("Organization short name (e.g. Soteria)", "NEXT_PUBLIC_ORG_NAME", { fallback: "Soteria" });
const orgFullName = await ask("Full display name (e.g. Soteria Church)", "NEXT_PUBLIC_ORG_FULL_NAME", { fallback: `${orgName} Church` });
const appName = await ask("App name shown in titles", "NEXT_PUBLIC_APP_NAME", { fallback: `${orgName} Assets` });
const contactTeam = await ask("Contact team wording (“Contact the …”)", "NEXT_PUBLIC_ORG_CONTACT_TEAM", { fallback: `${orgName} comms team` });
const emailPlaceholder = await ask("Login email placeholder", "NEXT_PUBLIC_LOGIN_EMAIL_PLACEHOLDER", { fallback: "you@example.org" });
const logoPath = await ask("Logo path under public/", "NEXT_PUBLIC_ORG_LOGO_PATH", { fallback: "/branding/logos/horizontal-navy.svg" });
const brandGuide = await ask("Enable built-in Brand Guide? (on/off)", "NEXT_PUBLIC_BRAND_GUIDE", { fallback: "off" });
const eventTypes = await ask("Photo event types (comma-separated, blank = default)", "NEXT_PUBLIC_EVENT_TYPES");

console.log("\n— Supabase (project settings → API) —");
const supabaseUrl = await ask("Project URL", "NEXT_PUBLIC_SUPABASE_URL");
const supabaseAnon = await ask("Anon key", "NEXT_PUBLIC_SUPABASE_ANON_KEY", { secret: true });
const supabaseService = await ask("Service role key", "SUPABASE_SERVICE_ROLE_KEY", { secret: true });
const databaseUrl = await ask("Database URL (session pooler)", "DATABASE_URL", { secret: true });

console.log("\n— AWS S3 —");
const awsRegion = await ask("Region", "AWS_REGION", { fallback: "us-east-1" });
const awsKey = await ask("Access key id", "AWS_ACCESS_KEY_ID", { secret: true });
const awsSecret = await ask("Secret access key", "AWS_SECRET_ACCESS_KEY", { secret: true });
const bucket = await ask("Bucket name", "S3_BUCKET_NAME", { fallback: `${slugify(orgName)}-dam-files` });
const s3PublicBase = await ask("Public base URL (blank = default)", "S3_PUBLIC_BASE_URL");

console.log("\n— AI + background jobs —");
const anthropicKey = await ask("Anthropic API key (tagging)", "ANTHROPIC_API_KEY", { secret: true });
const openaiKey = await ask("OpenAI API key (embeddings)", "OPENAI_API_KEY", { secret: true });
const inngestEventKey = await ask("Inngest event key", "INNGEST_EVENT_KEY", { secret: true });
const inngestSigningKey = await ask("Inngest signing key", "INNGEST_SIGNING_KEY", { secret: true });
const inngestAppId = await ask("Inngest app id", "INNGEST_APP_ID", { fallback: `${slugify(orgName)}-dam` });

console.log("\n— App —");
const appUrl = await ask("App URL", "NEXT_PUBLIC_APP_URL", { fallback: "http://localhost:3000" });

rl.close();

const lines = [
  "# Generated by scripts/setup.mjs — see docs/SELF_HOSTING.md",
  "",
  "# Organization (white-label identity, lib/config.ts)",
  `NEXT_PUBLIC_ORG_NAME=${orgName}`,
  `NEXT_PUBLIC_ORG_FULL_NAME=${orgFullName}`,
  `NEXT_PUBLIC_APP_NAME=${appName}`,
  `NEXT_PUBLIC_ORG_CONTACT_TEAM=${contactTeam}`,
  `NEXT_PUBLIC_LOGIN_EMAIL_PLACEHOLDER=${emailPlaceholder}`,
  `NEXT_PUBLIC_ORG_LOGO_PATH=${logoPath}`,
  `NEXT_PUBLIC_BRAND_GUIDE=${brandGuide}`,
  ...(eventTypes ? [`NEXT_PUBLIC_EVENT_TYPES=${eventTypes}`] : []),
  "",
  "# Supabase",
  `NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnon}`,
  `SUPABASE_SERVICE_ROLE_KEY=${supabaseService}`,
  `DATABASE_URL=${databaseUrl}`,
  "",
  "# AWS S3",
  `AWS_REGION=${awsRegion}`,
  `AWS_ACCESS_KEY_ID=${awsKey}`,
  `AWS_SECRET_ACCESS_KEY=${awsSecret}`,
  `S3_BUCKET_NAME=${bucket}`,
  ...(s3PublicBase ? [`S3_PUBLIC_BASE_URL=${s3PublicBase}`] : []),
  "",
  "# AI",
  `ANTHROPIC_API_KEY=${anthropicKey}`,
  `OPENAI_API_KEY=${openaiKey}`,
  "",
  "# Background jobs",
  `INNGEST_EVENT_KEY=${inngestEventKey}`,
  `INNGEST_SIGNING_KEY=${inngestSigningKey}`,
  `INNGEST_APP_ID=${inngestAppId}`,
  "",
  "# App",
  `NEXT_PUBLIC_APP_URL=${appUrl}`,
  "",
];

if (existsSync(ENV_PATH)) {
  copyFileSync(ENV_PATH, `${ENV_PATH}.bak`);
  console.log(`\nBacked up existing ${ENV_PATH} to ${ENV_PATH}.bak`);
}
writeFileSync(ENV_PATH, lines.join("\n"));
console.log(`Wrote ${ENV_PATH}`);

// Rename the seeded space (created by the initial migration) to this org.
if (supabaseUrl && supabaseService) {
  try {
    const { createClient } = await import("@supabase/supabase-js");
    const admin = createClient(supabaseUrl, supabaseService, {
      auth: { autoRefreshToken: false, persistSession: false },
    });
    const { data: space, error } = await admin
      .from("spaces")
      .update({ name: orgName, slug: slugify(orgName) })
      .eq("id", "00000000-0000-0000-0000-000000000001")
      .select()
      .maybeSingle();
    if (error) throw error;
    if (space) console.log(`Space renamed to "${space.name}" (${space.slug})`);
    else console.log("No seeded space found yet — run `npx supabase db push` first, then re-run setup.");
  } catch (err) {
    console.warn(`Could not rename the space (${err.message}) — you can re-run setup after migrations.`);
  }
}

if (VERIFY) {
  console.log("\nVerifying connections…");
  try {
    const { createClient } = await import("@supabase/supabase-js");
    const admin = createClient(supabaseUrl, supabaseService, {
      auth: { autoRefreshToken: false, persistSession: false },
    });
    const { error } = await admin.from("spaces").select("id").limit(1);
    if (error) throw error;
    console.log("  ✓ Supabase reachable, schema present");
  } catch (err) {
    console.warn(`  ✗ Supabase: ${err.message}`);
  }
  try {
    const { S3Client, HeadBucketCommand } = await import("@aws-sdk/client-s3");
    const s3 = new S3Client({
      region: awsRegion,
      credentials: { accessKeyId: awsKey, secretAccessKey: awsSecret },
    });
    await s3.send(new HeadBucketCommand({ Bucket: bucket }));
    console.log("  ✓ S3 bucket reachable");
  } catch (err) {
    console.warn(`  ✗ S3: ${err.message}`);
  }
}

console.log(`
Next steps:
  1. npx supabase link && npx supabase db push   # apply migrations
  2. npm run dev                                  # first sign-in becomes admin
  3. For production: add the same env vars to Vercel and set
     NEXT_PUBLIC_APP_URL to your domain.
Full runbook: docs/SELF_HOSTING.md
`);
